inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/**/*
    - config.ru
    - bin/**/*
    - tmp/**/*

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*_spec.rb'
    - 'spec/factories.rb'

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false
